# Generated by Django 3.2.7 on 2022-07-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
